version: 1
accounts:
- name: treasury
  coins:
  - 1000000ANDR
  - 10stake
- name: alice
  coins:
  - 20000ANDR
  - 200000000stake
- name: bob
  coins:
  - 10000ANDR
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5ANDR
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
- name: bob
  bonded: 50000000stake
genesis:
  app_state:
    staking:
      params:
        bond_denom: "stake"
    nibtdfvas:
      params:
        TokenOutflowPerBlock: 3
        DirectToValidatorPercent: 20
