version: 1
build:
  binary: andromedad
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
    
accounts:
- name: alice
  coins:
  - 20000andr
  - 200000000uandr
- name: bob
  coins:
  - 10000andr
  - 100000000uandr
faucet:
  name: bob
  coins:
  - 5andr
  - 100000uandr
  host: 0.0.0.0:4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000uandr
genesis:
  app_state:
    nibtdfvas:
      params:
        TokenOutflowPerBlock: 30
        DirectToValidatorPercent: 20
    staking:
      params:
        bond_denom: uandr
