name: golangci-lint
on:
  push:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

env:
  GO_VERSION: 1.22

jobs:
    golangci:
        name: golangci-lint
        runs-on: ubuntu-latest
        steps:
          - uses: actions/setup-go@v5
            with:
              go-version: ${{ env.GO_VERSION }}

          - uses: actions/checkout@v4

          - name: golangci-lint
            uses: golangci/golangci-lint-action@v6.1.0
            with:
              version: v1.61.0
              args: --timeout 15m
